indexed_folders:
  Books: /mnt/nas/Stephen/Books
  Health: /mnt/nas/Stephen/Health
  Learn: /mnt/nas/Stephen/Learn
  Magazines: /mnt/nas/Stephen/Magazines
  Movies: /mnt/nas/Movies

extensions:
  - epub
  - pdf
  - mp4
  - mkv
  - cbz
  - cbr
  - mp3

max_results: 100
fuzzy_threshold: 80
schedule_hour: 2
schedule_minute: 0
host: 0.0.0.0
port: 8080
